# -*- coding:utf-8 -*-

from saklient.errors.httpconflictexception import HttpConflictException
from saklient.errors.httpconflictexception import HttpConflictException

# module saklient.cloud.errors.ipv6netalreadyattachedexception

class IpV6NetAlreadyAttachedException(HttpConflictException):
    ## 要求された操作を行えません。ConnectedなIPv6ネットワークが既に割り当て済みです。
    
    # (class field) default_message = "要求された操作を行えません。ConnectedなIPv6ネットワークが既に割り当て済みです。"
    
    pass
