# -*- coding:utf-8 -*-

from saklient.errors.httpconflictexception import HttpConflictException
from saklient.errors.httpconflictexception import HttpConflictException

# module saklient.cloud.errors.limitcountinnetworkexception

class LimitCountInNetworkException(HttpConflictException):
    ## 要求を受け付けできません。ネットワーク内リソース数上限により、リソースの割り当てに失敗しました。
    
    # (class field) default_message = "要求を受け付けできません。ネットワーク内リソース数上限により、リソースの割り当てに失敗しました。"
    
    pass
