# -*- coding:utf-8 -*-

from saklient.errors.httpnotfoundexception import HttpNotFoundException
from saklient.errors.httpnotfoundexception import HttpNotFoundException

# module saklient.cloud.errors.resourcepathnotfoundexception

class ResourcePathNotFoundException(HttpNotFoundException):
    ## 対象が見つかりません。パスに誤りがあります。
    
    # (class field) default_message = "対象が見つかりません。パスに誤りがあります。"
    
    pass
